name: flutter_hms_gms_availability_example
description: Demonstrates how to use the flutter_hms_gms_availability plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_hms_gms_availability:
    path: ../

flutter:
  uses-material-design: true
