name: flutter_hms_gms_availability
description: Flutter plugin to detect HMS and GMS availability. Always return False in iOS.
version: 3.10.0+eh
homepage: https://github.com/trilobyte-my/flutter_hms_gms_availability

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chimou.flutter_hms_gms_availability
        pluginClass: FlutterHmsGmsAvailabilityPlugin
      ios:
        pluginClass: FlutterHmsGmsAvailabilityPlugin
