name: flutter_hms_gms_availability
description: Flutter plugin to detect HMS and GMS availability. Always return False in iOS.
version: 3.0.0
homepage: https://github.com/trilobyte-my/flutter_hms_gms_availability

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.chimou.flutter_hms_gms_availability
        pluginClass: FlutterHmsGmsAvailabilityPlugin
      ios:
        pluginClass: FlutterHmsGmsAvailabilityPlugin
